"""Initial migration

Revision ID: 58efcb94d4ac
Revises: 
Create Date: 2026-07-21 18:43:08.537731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58efcb94d4ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourism_statistics')
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geo_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nuts_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('regions_pkey')),
    sa.UniqueConstraint('geo', name=op.f('regions_geo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tourism_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('arrivals', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overnights', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('occupancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turnover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('tourism_statistics_region_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tourism_statistics_pkey'))
    )
    # ### end Alembic commands ###
